### ISSUE TITLE
性能优化：表索引

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#105]
# Query_time: 0.359422  Lock_time: 0.000043 Rows_sent: 167  Rows_examined: 499
SET timestamp=1492412526;
SELECT tb_student_detection.*, tb_file.file_path as file_path
            FROM tb_student_detection
            LEFT JOIN tb_file ON  tb_student_detection.file_img_id = tb_file.id  AND tb_file.deleted = 0
            WHERE tb_student_detection.deleted = 0
            AND tb_student_detection.`status` = 1 AND tb_student_detection.student_id = '420' ORDER BY created DESC;
需要增加二级索引，按日期排序

**Comment by jsonyj** [comment]
效率低的原因在于，ORDER BY created DESC;没有指定哪张表的created，导致mysql花费时间，先修改为
ORDER BY tb_student_detection.created DESC;效率提升

**Comment by jsonyj** [comment]
explain结果显示extar使用了Using temporary; Using filesort，导致效率较低，需优化
