### ISSUE TITLE
性能优化：再次优化

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#106]
Query_time: 0.323655  Lock_time: 0.000090 Rows_sent: 29  Rows_examined: 20648
SET timestamp=1492391079;
SELECT tb_student.*, tb_school.title AS school_title,tb_school.key_active_time, tb_class.title AS class_title, tb_student_parent.relation_id, tb_school_parent.type AS parent_type, tb_student_parent.qrcode_url, tb_student_parent.qrcode_url_old
            FROM tb_student
            LEFT JOIN tb_student_parent ON tb_student_parent.student_id = tb_student.id AND tb_student_parent.parent_id IN
              (
              SELECT id FROM tb_school_parent WHERE phone = '18508148488' and deleted = 0
              )
            LEFT JOIN tb_school_parent ON tb_school_parent.id = tb_student_parent.parent_id AND tb_school_parent.deleted = 0
            LEFT JOIN tb_school ON tb_school.id = tb_student.school_id
            LEFT JOIN tb_class ON tb_class.id = tb_student.class_id
            WHERE tb_student.deleted = 0 AND tb_student_parent.deleted = 0 ORDER BY tb_student.created DESC;

**Comment by jsonyj** [comment]
SELECT tb_student.*, tb_school.title AS school_title,tb_school.key_active_time, tb_class.title AS class_title, tb_student_parent.relation_id, tb_school_parent.type AS parent_type, tb_student_parent.qrcode_url, tb_student_parent.qrcode_url_old
FROM tb_student
LEFT JOIN (select tb_student_parent.* from tb_student_parent,tb_school_parent where tb_school_parent.phone = 18980322478 and tb_student_parent.parent_id = tb_school_parent.id ) as tb_student_parent ON tb_student_parent.student_id = tb_student.id
LEFT JOIN tb_school_parent ON tb_school_parent.id = tb_student_parent.parent_id AND tb_school_parent.deleted = 0
LEFT JOIN tb_school ON tb_school.id = tb_student.school_id
LEFT JOIN tb_class ON tb_class.id = tb_student.class_id
WHERE tb_student.deleted = 0 AND tb_student_parent.deleted = 0 and tb_class.deleted = 0 and tb_school_parent.deleted = 0 and tb_school.deleted = 0 ORDER BY tb_student.created DESC
