### ISSUE TITLE
晨检的相关sql需要优化

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#120]
SELECT
                tb_student.name, tb_student.gender,
                tb_class.title,tb_ic_card.ic_number
                ,detection.height
                ,detection.weight
                ,detection.temperature  FROM tb_student
                LEFT JOIN tb_class ON tb_class.id = tb_student.class_id
                LEFT JOIN tb_ic_card ON tb_student.rfid = tb_ic_card.rfid
                LEFT JOIN (SELECT tmp.student_id,tmp.height,tmp.weight,tmp.temperature FROM tb_student_detection tmp
                LEFT JOIN tb_student ON tmp.student_id=tb_student.id
                WHERE tmp.deleted=0 AND tmp.status=1
                GROUP BY tmp.student_id) AS detection ON detection.student_id =tb_student.id
                WHERE tb_student.deleted = 0  AND tb_student.school_id = '5' ORDER BY tb_class.title ASC

describe 整个sql语句，中间的子查询范围太大
+----+-------------+------------+-------------+--------------------------------------------+--------------------------------------------+---------+----------------------------------+--------+-----------------------------------------------------------------------------------------------------------+
| id | select_type | table      | type        | possible_keys                              | key                                        | key_len | ref                              | rows   | Extra                                                                                                     |
+----+-------------+------------+-------------+--------------------------------------------+--------------------------------------------+---------+----------------------------------+--------+-----------------------------------------------------------------------------------------------------------+
|  1 | PRIMARY     | tb_student | index_merge | school_id,index_schoolid_delete_tb_student | school_id,index_schoolid_delete_tb_student | 4,5     | NULL                             |    176 | Using intersect(school_id,index_schoolid_delete_tb_student); Using where; Using temporary; Using filesort |
|  1 | PRIMARY     | tb_class   | eq_ref      | PRIMARY                                    | PRIMARY                                    | 4       | xiaonuo_test.tb_student.class_id |      1 |                                                                                                           |
|  1 | PRIMARY     | tb_ic_card | ref         | rfid                                       | rfid                                       | 153     | xiaonuo_test.tb_student.rfid     |      1 |                                                                                                           |
|  1 | PRIMARY     | <derived2> | ALL         | NULL                                       | NULL                                       | NULL    | NULL                             |   3996 |                                                                                                           |
|  2 | DERIVED     | tmp        | ALL         | NULL                                       | NULL                                       | NULL    | NULL                             | 186299 | Using where; Using temporary; Using filesort                                                              |
|  2 | DERIVED     | tb_student | eq_ref      | PRIMARY                                    | PRIMARY                                    | 4       | xiaonuo_test.tmp.student_id      |      1 | Using index                                                                                               |
+----+-------------+------------+-------------+--------------------------------------------+--------------------------------------------+---------+----------------------------------+--------+--------

**Comment by jsonyj** [comment]
SELECT
	tb_student. NAME,
	tb_student.gender,
	tb_class.title,
	tb_ic_card.ic_number,
	detection.height,
	detection.weight,
	detection.temperature
FROM tb_student
LEFT JOIN tb_class ON tb_class.id = tb_student.class_id
LEFT JOIN tb_ic_card ON tb_student.rfid = tb_ic_card.rfid
LEFT JOIN tb_student_detection as detection ON detection.student_id = tb_student.id
WHERE tb_student.deleted = 0
AND tb_student.school_id = '4'
group by tb_student.id
ORDER BY tb_class.title ASC;
取消临时表。
