### ISSUE TITLE
微信端获取晨检数据sql需要优化

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#121]
SELECT tb_student_detection.*, tb_file.file_path as file_path
                            FROM tb_student_detection
                            LEFT JOIN tb_file ON  tb_student_detection.file_img_id = tb_file.id  AND tb_file.deleted = 0
                            WHERE tb_student_detection.deleted = 0
                            AND tb_student_detection.`status` = 1 AND tb_student_detection.student_id = '773' ORDER BY tb_student_detection.created DESC;
需要将b_student_detection.student_id = '773'放到前面去，这样速度就会好很多

**Comment by stephenwang2017** [comment]
微信StudentDetectionModel.php
SELECT tb_student_detection.*, tb_file.file_path as file_path
                            FROM tb_student_detection
                            LEFT JOIN tb_file ON  tb_student_detection.file_img_id = tb_file.id  AND tb_file.deleted = 0
                            WHERE tb_student_detection.deleted = 0
                            AND tb_student_detection.`status` = 1 AND tb_student_detection.student_id = '773' ORDER BY tb_student_detection.created DESC;

   修改为
                                        
    SELECT tb_student_detection.*, tb_file.file_path as file_path
                                FROM tb_student_detection
                                LEFT JOIN tb_file ON  tb_student_detection.file_img_id = tb_file.id  AND tb_file.deleted = 0
                                WHERE   tb_student_detection.student_id = '773' and tb_student_detection.deleted = 0
                                AND tb_student_detection.`status` = 1  ORDER BY tb_student_detection.created DESC;

**Comment by stephenwang2017** [comment]
每一个条件查询会生成一个临时表，所以第一个临时表如果能够最大程度缩小查询范围，则速度会改善很多

**Comment by veraGe** [comment]
StudentDetectionModel.php中getDetection中函数修改查询studentId查询位置

**Comment by liaoqiangadapt** [comment]
过滤能力强的sql语句放在最前面，最先执行，提高查询效率（针对MySQL，oracle不是这样）
