### ISSUE TITLE
detection表常有两条数据，相同的数据为什么

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#127]
http://image-didanuo.oss-cn-shenzhen.aliyuncs.com/detection/20170505/652bd5d6873c499cf2436df7bc090e25.jpg

**Comment by stephenwang2017** [comment]
是不是重复提交的问题？如果是是不是也可以采用客户端标示位来解决，目前通过数据库校验是不可行的，漏洞很大的，如果客户端解决，具体的方案细节？除此之外其他接口是否也有这个问题？

**Comment by stephenwang2017** [comment]
通过查dection表图片路径，可查到同一时刻有两条，另外可以查看是否这个会导致发不出推送信息

**Comment by veraGe** [comment]
误诊
