### ISSUE TITLE
页面数据提交多次问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#131]
通讯录提交提交多次锁定

**Comment by stephenwang2017** [comment]
解决此问题之后，要横向思考其他还有哪里也有这个问题，特别是用户使用的界面，每一个这种情况具体分析具体解决

**Comment by veraGe** [comment]
在添加学生和教职工中，使用标记，当用户向后台提交请求时，要用标记进行判断是否可以向后台提交请求
