### ISSUE TITLE
重复学生数据的定位和清理

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#132]
目前有些用户重复了，包括姓名、生日，每个应该具体分析，排除重复的

**Comment by jsonyj** [comment]
重复：樊川，李荣宽，张子涵，大王，刘鑫宇。
樊川，出现两次。但是学校不同，不做改变；李荣宽，出现两次，确认为重复数据；张子涵，出现三次，其中两次重复；大王，出现两次，但是班级不同；出现两次，但是学校不同
