### ISSUE TITLE
晨检推送消息有时候没有

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#14]

**Comment by stephenwang2017** [comment]
微信有百分之一的失败率，而我们的代码反复发三次，需要重新发，需要了解微信发送失败标志位

**Comment by stephenwang2017** [comment]
如果发送还是失败的，增加一个半小时后再发，只增加一次再发

**Comment by stephenwang2017** [comment]
最近还反馈有家长没有收到信息，需要再跟踪

**Comment by jsonyj** [comment]
可以考虑是否是因为家长更换了手机号码的原因？

**Comment by jsonyj** [comment]
@stephenwang2017

**Comment by jsonyj** [comment]
红黄蓝幼儿园，林子涵小朋友的妈妈在2017-05-10没有接收到微信消息
tb_student
4438	1553998964	2661	7	36	林子涵
tb_student_parent
7570	7	36	4438	6858
tb_school_parent
6858	7		13880165515
tb_parent
3644	4997		13880165515
tb_weiChat
4997	oVnnvv8LDT4463CRe_PbflbsvXPA
tb_weiChat_push
431461	oVnnvv8LDT4463CRe_PbflbsvXPA
433873	oVnnvv8LDT4463CRe_PbflbsvXPA

**Comment by stephenwang2017** [comment]
早期问题，关闭
