### ISSUE TITLE
新增学生及家长，只生成一张二维码图片，如果幼儿园断网，则会出现问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#144]
如果第二天网络是通的，会生成新的图片，并将刷新老图片，则没有此问题，如果，第二天网络是不通的，老图片为空，则会报不识别。（此问题，该有谁记录？？）

**Comment by jsonyj** [comment]
新增用户，根据正在使用的key已经，当天新生成的key，生成两张二维码。
