### ISSUE TITLE
管理员控制台增加一项功能

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#146]
学校 学生 体温 实际体温 时间 ，有选择时间范围，时间段

**Comment by veraGe** [comment]
Admin/App/Controllers/SchoolController.php
Admin/App/Models/StudentDetectionModel.php
Admin/App/Templates/School/studentDetectionData.html
Admin/Config/Code.inc.php。加入查询指定学校学校，时间段，并且导出学生晨检信息excel
