### ISSUE TITLE
小朋友生日日期有时候不对

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#165]
需要核查sql语句写的是否正确，许总反馈的问题，小胖

**Comment by stephenwang2017** [comment]
不知道是不是这个原因，有时候绑定的时候，输入了正确的生日，也绑定不成功，所以要检查下

**Comment by veraGe** [comment]
WeiChat/studentModel.php/getStudentListByParentPhone()中一下sql可能有问题
SELECT tb_student.*, tb_school.title AS school_title,tb_school.key_active_time, tb_class.title AS class_title, tb_student_parent.relation_id, tb_school_parent.type AS parent_type, tb_student_parent.qrcode_url, tb_student_parent.qrcode_url_old, tb_student_parent.qrcode_school_key_old,tb_school.key
          FROM tb_student
          LEFT JOIN (select tb_student_parent.* from tb_student_parent,tb_school_parent where tb_school_parent.phone = '{$parentPhone}' and tb_student_parent.parent_id = tb_school_parent.id ) as tb_student_parent ON tb_student_parent.student_id = tb_student.id
          LEFT JOIN tb_school_parent ON tb_school_parent.id = tb_student_parent.parent_id AND tb_school_parent.deleted = 0
          LEFT JOIN tb_school ON tb_school.id = tb_student.school_id
          LEFT JOIN tb_class ON tb_class.id = tb_student.class_id
          WHERE tb_student.deleted = 0 AND tb_student_parent.deleted = 0 and tb_class.deleted = 0 and tb_school_parent.deleted = 0 and tb_school.deleted = 0 ORDER BY tb_student.created DESC

**Comment by stephenwang2017** [comment]
已经清楚了，根据电话查出来5个人，倒数两个用户小哈和小胖，分别是11-6日，11-8，两个学生很接近，应该是按的时候误操作，让人以为串了，从代码上判断，没有问题
