### ISSUE TITLE
数据库短时间因为阻塞等原因接入多条数据，可能是重复的数据，如何做到排重

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#171]
每次晨检一条数据，但是由于网络问题，可能会多次发送，需要有一个排重机制

**Comment by stephenwang2017** [comment]
判断一个数据是否重复，采用联合特征，serviceid studentid createdate 三个点，同时不在直接写入数据库，采用缓存机制，将特征写入缓存，每次入库的时候再校验，同时也要管理好缓存，对于缓存数据定时做清理

**Comment by jsonyj** [comment]
增加缓存机制，缓存一小时。
