### ISSUE TITLE
体重的曲线显示太直白

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#18]
需要用控件将曲线做的更圆润

**Comment by veraGe** [comment]
暂时不关闭，作为需求存在

**Comment by veraGe** [comment]
WeiChat/App/Controllers/ReportController.php
WeiChat/App/Models/ChartModel.php
WeiChat/App/Templates/Parent/report.html
WeiChat/App/Templates/Query/index.html
WeiChat/App/Templates/School/playVideo.html
WeiChat/Webroot/css/xiaonuo-addone.css
将月报改成当前月的前三个月，成为季报，在ChartModel.php中处理获取到的数据
