### ISSUE TITLE
导入学生信息失败

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#209]

**Comment by stephenwang2017** [comment]
![1](https://user-images.githubusercontent.com/24886936/29647645-d208714e-88bc-11e7-9685-53ddace158e4.png)
![default](https://user-images.githubusercontent.com/24886936/29647648-d47ffd8e-88bc-11e7-83ec-9bfe7f573c61.png)
[多营.xlsx](https://github.com/didanoDevelopers2017/xiaonuo/files/1247621/default.xlsx)

**Comment by liaoqiangadapt** [comment]
OK啦
