### ISSUE TITLE
超级管理员显示晨检数据，没有将未识别的晨检信息显示出来

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#218]
表里面student_id=0的数据就是没有识别的数据，相应的在表tb_student_claim表里面可以看到学校id,因此，我以为在tb_student_detection中增加school_id字段比较合适，新增字段后，将老数据不齐即可，老数据分为两种，一种是student_id=0,一种不为0的，采用分别的方法查到school_id写入

**Comment by liaoqiangadapt** [comment]
tb_student_detection已增加school_id字段，已设置为，为0或非0

**Comment by liaoqiangadapt** [comment]
解决方法：
加下拉：所有，未识别，识别

**Comment by liaoqiangadapt** [comment]
![2017-10-26_171442](https://user-images.githubusercontent.com/13218359/32044978-aaad0e16-ba71-11e7-8075-1c9b5b0f0088.png)
