### ISSUE TITLE
园长添加老师后，进入宝贝中心，居然跳转到绑定的选择家长手机号等界面

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#222]
老师余霞 13881636855  朱思雨 1811653365 ，后台将这两个删除掉，重新绑定，就可以从宝贝中心进入

**Comment by underhill6** [comment]
绑定的老师在tb_staff_class表中没有数据，即没有绑定对应的班级，就会跳转到宝贝中心没有数据；
解决方案：增加对老师未绑定班级时的提示语，可以让老师知道不能正常显示的原因。
