### ISSUE TITLE
学校管理后台职工编辑会做手机号的校验;

### ISSUE THREAD

**Issue by underhill6** [didanoDevelopers2017/xiaonuo#223]
1. 学校管理后台职工编辑会做手机号的校验,之前有手机号再编辑就不能更新成功;

**Comment by stephenwang2017** [comment]
这个检查是不是应该要排除自己，理论上来说一个医生变成一个普通老师也是可以的撒

**Comment by veraGe** [comment]
在一个学校中，现在是一个电话号码只能对应一个职工身份，若自己修改自己成为其他职工是可以的。如果编辑提示该职工电话号码已存在，说明本学校该电话号码对应了多个职工身份。
