### ISSUE TITLE
耿园长的二维码居然是龙腾的

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#226]
我这边河北的园长，二维码怎么是龙腾的码，电话:13111630373
![img_3309](https://user-images.githubusercontent.com/24886936/29955430-22d3b4b6-8f12-11e7-8e55-e4c41733d75a.JPG)

**Comment by liaoqiangadapt** [comment]
测试了下，没有问题，可能是后台开发人员调试时动到哪儿了
