### ISSUE TITLE
大足金桂贝贝幼儿园老师绑定成功后，点击进入宝贝中心依然要跳到绑定页面

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#229]
几乎所有老师在8月30日，9月1日出现这种状况，河北涿州的教职工也出现这样得问题

**Comment by underhill6** [comment]
1.tb_staff_class表中老师对应的班级已经删除,但是在学校后台里还可以看见这个老师对应的班级;
