### ISSUE TITLE
老师和班级表映射可能还有问题，特别是删除状态的

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#247]
有个老师进入宝贝中心显示没有找到与她匹配的班级 实际上后台已经绑定到芬尼奇班了 我把她删除之后重新创建就可以了

**Comment by veraGe** [comment]
重新设置老师可以一对多的关系，原来删除老师是用的delete，将delete改成update，删除时将deleted状态修改为1
