### ISSUE TITLE
照片墙的图片错误

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#260]
哈罗宝贝幼儿园胡可馨小朋友的照片墙 是另一家开心幼儿园小朋友的
照片错乱是在5月之前，是不是这张照片是4月份的，估计属于错乱的
![wechatimg626](https://user-images.githubusercontent.com/24886936/30314396-3109b5a2-97d3-11e7-9558-87716a5283ea.jpeg)

**Comment by veraGe** [comment]
有两个同名同姓同生日的胡可馨，哈罗宝贝school_id=8的胡可馨小朋友student_id = 3314,开心幼儿园school_id = 19的胡可馨小朋友student_id = 3092。student_id为3092的小朋友晨检照片只有一张，student_id为3314的小朋友的100多张历史照片，人工对比，删除了不是该小朋友的照片。并且没有查出student_id为3314的小朋友照片中，没有student_id为3092的小朋友的照片
