### ISSUE TITLE
开心幼儿园陈老师报告雷奥班吴靖雅妈妈打开二维码是白板

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#264]
![screenshot_2017-09-13-15-16-34-443_com tencent mm_ b ece837a](https://user-images.githubusercontent.com/24886936/30364524-26ebda22-9897-11e7-85be-8752fa61f312.png)

**Comment by liaoqiangadapt** [comment]
是“吴靖雅”哈
