### ISSUE TITLE
php后台，在删除学生信息时有漏洞

### ISSUE THREAD

**Issue by yang55** [didanoDevelopers2017/xiaonuo#266]
在删除学生的信息时，当前是删除学生表tb_student，家长表tb_student_parent
在删除操作时应该进行3张表的操作，除上面两张外，好要进行t_school_parent表的删除操作。

**Comment by veraGe** [comment]
对单独删除家长，删除学生，删除班级时，一起更新tb_school_parent表
School/App/Controllers/ParentController.php
 School/App/Controllers/StudentController.php
School/App/Models/ClassModel.php
School/App/Models/SchoolParentModel.php
School/App/Models/StudentModel.php
