### ISSUE TITLE
php学校后台，学校家长不存在，学生下面的家长就查询不出来

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#267]
在通讯录中，家长的现实只进行查询tb_student_parent表中存在（不管在tb_school_parent中的家长是否存在）都会蒋电话号码和家长都会查询出来，而在php后台，在查询tb_school_parent时，只要里面的家长不存在，不管tb_student_parent中的家长存不存在，查询出来的结果都是没有家长信息的。和通讯录有一点区别。

**Comment by veraGe** [comment]
修改通讯录
