### ISSUE TITLE
php学校后台sql出现问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#268]
php sql在查询学生信息的时候，学生绑定有ic，但是在ic卡表中的数据是删除的状态，就查询不出学生的信息，要改为，就算ic卡的数据存在删除的状态，查询学生信息时，学生信息会查出来，最多就是ic卡的信息查询不出来。

**Comment by veraGe** [comment]
学生IC卡单独查出，家长IC卡查询做临时表查询。
 School/App/Models/SchoolParentModel.php
School/App/Models/StaffModel.php
 School/App/Models/StudentModel.php
