### ISSUE TITLE
 ​所有关联tb_student_detection表的查询都需要重新整理

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#27]
​所有关联tb_student_detection表的查询都需要重新整理，接口和业务实际上都只是要去tb_student_detection表的某一行数据，如下写法是有问题的，先取tb_student_detection表所有数据，然后做左连接查询，效率奇低。应该反其道而行，先查一条数据，然后再关联tb_student_detection表，这样效率就高
   SELECT tb_student_detection.*, tb_file.file_path as file_path
            FROM tb_student_detection
            LEFT JOIN tb_file ON  tb_student_detection.file_img_id = tb_file.id  AND tb_file.deleted = 0
            WHERE tb_student_detection.deleted = 0
            AND tb_student_detection.`status` = 1 ORDER BY created DESC;
   tb_student_detection.file_img_id实际上是某个学生的关联数据

**Comment by jsonyj** [comment]
ORDER BY created DESC;原本按照created排序，现在修改为按照id排序
