### ISSUE TITLE
php后台进行ic卡的绑定出现问题 

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#270]
通讯录的绑定规则：只要在学生表或者家长表查询deleted=0的ic卡数据，如果没有查询到不管ic卡所属的学校是哪个，都可以进行绑定，然而，php后台只要ic卡不属于这个学校，但是没有人绑定过，都不可以进行绑定，所以在php后台绑定不属于该学校的ic卡都会出现问题（绑定状态为0的除外）

**Comment by veraGe** [comment]
在school模块中删除关于IC学校ID的操作
School/App/Controllers/StaffController.php
School/App/Controllers/StudentController.php
School/App/Models/SchoolParentModel.php
School/App/Models/StaffModel.php
School/App/Models/StudentModel.php
