### ISSUE TITLE
乐山乐天天幼儿园，刘一梅老师绑定的老师卡，昨天可以刷卡，今天上班刷卡不成功

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#273]
有可能名字搞混，或者是夏瑛老师

**Comment by liaoqiangadapt** [comment]
微信用户：oVnnvv__WfmTz1XxiOwoey1sav-o  念旧人

**Comment by liaoqiangadapt** [comment]
![image](https://user-images.githubusercontent.com/13218359/30846911-0575475e-a2cc-11e7-912a-591951058f28.png)
可以了
