### ISSUE TITLE
打开角色绑定有时会跳转到二维码界面

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#278]
![screenshot_20170915-073857_ b 2ad4552](https://user-images.githubusercontent.com/24886936/30470154-2e314ab6-9a26-11e7-8523-7ca4f6d801f9.png)

**Comment by veraGe** [comment]
将正式服务上绑定部分的代码检查过，没有要去跳转到二维码界面的代码。
