### ISSUE TITLE
超级管理员页面出现问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#286]
输入正确的用户名密码和验证码，即时验证码输入错误，也不弹出“验证码错误”的提示框，只是回转到当前页面，怀疑三台服务器中的一个有问题

**Comment by stephenwang2017** [comment]
昨天华总，报登录学校页面也总进不去，估计也是类似问题

**Comment by veraGe** [comment]
代码比对3台服务器一致。多次使用本地和测试服务器也没有出现过这种情况

**Comment by stephenwang2017** [comment]
apache配置问题，已经搞定
