### ISSUE TITLE
学校后台录入家长，仍然出现student_parent-school_parent 一对多的情况

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#289]

**Comment by veraGe** [comment]
学校后台限制一个学生中家长的电话号码不能重复，微信绑定中也会做不能重复绑定，在老的规则中，若家长的电话存在在tb_school_parent中，则就会使用老的id，这样就会出现一对多的情况。现在将这个去掉，只要家长绑定一个学生，就会在tb_school_parent表中新增加一条数据，形成与学生一一对应的关系。
WeiChat/App/Controllers/BindController.php
WeiChat/App/Models/WeichatBindModel.php
