### ISSUE TITLE
照片传错的问题，小朋友A的照片发给了小朋友B，并且小朋友B是没有认错的状态下。

### ISSUE THREAD

**Issue by veraGe** [didanoDevelopers2017/xiaonuo#29]
龙寅初 student_id = 4325

2017-03-07  id = 132898
http://image-didanuo.oss-cn-shenzhen.aliyuncs.com/detection/20170307/6efa454c816056ed40ca7129e2f87899.jpg

2017-03-02  id = 122691
http://image-didanuo.oss-cn-shenzhen.aliyuncs.com/detection/20170302/002bf71b8b172682df6e9dd077ee6df6.jpg

2017-03-01  id = 120697
http://image-didanuo.oss-cn-shenzhen.aliyuncs.com/detection/20170301/658eea51ec06010209267cab55b771a5.jpg

**Comment by stephenwang2017** [comment]
余杰将上传文件生成临时文件步骤，取消掉，这部分是以前的方式，现在改用oss不再需要这一部分。
