### ISSUE TITLE
金太阳幼儿园二维码问题

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#290]
该校大约有三十多个家长使用二维码，大多数使用刷卡，目前报的问题是刷二维码的问题，其中有二十多家长刷二维码报不识别

**Comment by stephenwang2017** [comment]
该校目前，有8台刷卡机注册，主要用在校车上

**Comment by stephenwang2017** [comment]
![411](https://user-images.githubusercontent.com/24886936/30675594-068dab98-9eb4-11e7-9e07-1d967ee06ecc.png)
![412](https://user-images.githubusercontent.com/24886936/30675599-096081ce-9eb4-11e7-8847-800a5cdec730.png)
![413](https://user-images.githubusercontent.com/24886936/30675603-0adb24fa-9eb4-11e7-9fde-f7535118c984.png)
![414](https://user-images.githubusercontent.com/24886936/30675606-0ffe6050-9eb4-11e7-9095-8389fb1b1568.png)
![415](https://user-images.githubusercontent.com/24886936/30675611-14cab372-9eb4-11e7-97f9-4677bbc76088.png)
![416](https://user-images.githubusercontent.com/24886936/30675615-160d9f10-9eb4-11e7-88e0-a7f0c583dd54.png)
![417](https://user-images.githubusercontent.com/24886936/30675618-17a15614-9eb4-11e7-9243-087849296bbd.png)

**Comment by liaoqiangadapt** [comment]
找不到原来的key很难，除非先联网上获取一次
