### ISSUE TITLE
有个小朋友妈妈能收到晨检，爸爸收不到

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#296]
![wechatimg278](https://user-images.githubusercontent.com/24886936/30735949-69f147d0-9fb3-11e7-8e8f-457f0fa648a0.jpeg)

**Comment by underhill6** [comment]
1.李雨阳小朋友有录入了三个重复(同校同班同名)学生信息；
2.前两个学生信息爸爸妈妈分别有绑定的学生家长关系，第三条信息有奶奶绑定的学生家长对应关系；
3.查看了数据库消息推送表，爸爸妈妈在9月22日早上都有成功发送消息的记录；
4.推测原因可能是学生数据冗余导致数据有误；
5.操作：删除后两条学生信息数据，并在数据库中重新将学生家长关系对应到第一个学生信息数据上。
