### ISSUE TITLE
现在家长收不到孩子的晨检信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#299]
泸州的开心幼儿园芬尼奇班的牟云朵小盆友以前的晨检接送卡绑定不起，我从新换张已给绑定。但是家长的二维码又出现以下情况

![wechatimg12](https://user-images.githubusercontent.com/24886936/30891523-68fbf9f4-a366-11e7-8751-ab1f3a2c4b03.jpeg)
![wechatimg14](https://user-images.githubusercontent.com/24886936/30891530-7046243c-a366-11e7-8df5-fc3a974bad5a.jpeg)

**Comment by veraGe** [comment]
小朋友student_id = 18250,家长parent_id =37697，openid="oVnnvv8SuOez-BnTy69B_XQURZs8"该小朋友只有一个家长。
如若问题描述的是家长晨检信息收不到，该在9月25号被删除后，又新创建的student_id = 18250。新建以来，小朋友一直以来的晨检数据库中就只存有一条，日期为2017年9月26号，并且在26号时，家长是有推送信息的，推送消息的id=892834。9月27号小朋友并有做晨检。
如若问题描述的是家长绑定小朋友，如果家长和小朋友的绑定关系存在后，就不能重复绑定，会导致tb
_school_parent和tb_student_parent中数据错乱。
