### ISSUE TITLE
绑定不上

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#303]
![default](https://user-images.githubusercontent.com/24886936/31329202-85b9ff2e-ad0b-11e7-91fc-03862d980d71.jpeg)

**Comment by stephenwang2017** [comment]
这个小朋友毕业留园，老师之前把名字删除了，但是后面留院后老师又在后台增加了这个小朋友，问题是他的爸爸妈妈绑定不了了。

**Comment by veraGe** [comment]
该小朋友和妈妈的绑定关系已经存在，爸爸绑定不上，就绑定前的条件验证根据电话号码进行了修改
