### ISSUE TITLE
三幼 小三班 田紫蜜妈妈绑定收不到验证码

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#304]
三幼 小三班 田紫蜜妈妈 电话18502802737
绑定收不到验证码
10月9日
按约定每个手机号不能当日收到不超过5条，短信
那么需要去查
1，短信平台是否向这个手机号发过短信
2，发过多少条
然后进一步查

**Comment by veraGe** [comment]
用户短信记录都有，通过联系互亿的客服，客服反馈说，用户回复退订过106通道短信或者短信发送过于频繁就会被运营商加入黑名单的。
1、这个运营商黑名单没有办法去控制，需要取消黑名单，只有去联系互亿的客服去解决
2、无法知道用户是因为何种原因被运营商加入了黑名单
3、用户被加入了黑名单，我们从互亿的平台上无法得知，就只能去联系互亿的客服去查询
