### ISSUE TITLE
三幼的赵周远刷卡是无效ID卡

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#307]
![wechatimg2268](https://user-images.githubusercontent.com/24886936/31532138-05f6d88c-b01e-11e7-88b5-d0e8ee59077b.jpeg)

**Comment by liaoqiangadapt** [comment]
赵翢远 ！！

**Comment by liaoqiangadapt** [comment]
这个还需确认下，问题暂时不关
