### ISSUE TITLE
IC卡管理功能，只显示卡状态类型等，为什么不能输入卡号来查询对应小朋友名字

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#314]
实施人员不方便

**Comment by veraGe** [comment]
Admin/App/Controllers/IcCardController.php
Admin/App/Models/IcCardModel.php
Admin/App/Templates/IcCard/bindInfo.html
 Admin/Config/Code.inc.php
在IC管理模块增加一个查询IC绑定信息模块
