### ISSUE TITLE
17784796693   李玲  酉阳欣鑫幼儿园  收不到验证码

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#316]

**Comment by veraGe** [comment]
该手机号到1点多时，已经发送了5次短信，后面又发过很多次短信。。通过联系互亿平台的客服，查到今天成功发送了前面几次的短信了。并且没有加入黑名单，如果用户收不到短信，就是用户自己的手机最了短信拦截设置，或者其他的操作
