### ISSUE TITLE
数据完整性检查，安卓、刷一刷、小诺，挨个检查一遍

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#322]
![wechatimg2878](https://user-images.githubusercontent.com/24886936/32203162-6a12d8d2-be1c-11e7-88ce-af8adb3ddd01.jpeg)

**Comment by liaoqiangadapt** [comment]
可是可以追查，这个问题廖全龙排查比较妥

**Comment by stephenwang2017** [comment]
三个客户端都有数据包校验，长度验证，有10位数字，如果不够前面添加0
