### ISSUE TITLE
晨检描述和实际情况可能有误，王舒瑶，大六班

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#324]
![img_20171106_091703_ b 37155f4](https://user-images.githubusercontent.com/24886936/32421611-5f3b72e4-c2d5-11e7-9055-95721c34e1f7.jpg)

**Comment by liaoqiangadapt** [comment]
微信模板消息是没问题的，这个问题是前端解析问题。这个学生ID 是 18629

**Comment by LingRen** [comment]
已解决
