### ISSUE TITLE
月报每隔一分钟执行

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#43]
1，每分钟执行一次，在早上7点之前，为何？
2，sql语句效力不高需要0.34秒
SET timestamp=1489526042;
SELECT tb_student.id AS student_id, tb_report_month.id 
            FROM tb_student
            LEFT JOIN tb_report_month ON tb_student.id = tb_report_month.student_id AND start = '2017-03-01 00:00:00' AND end = '2017-03-31 23:59:59'
            WHERE tb_student.deleted = 0 AND tb_report_month.id IS NULL LIMIT 30;

**Comment by jsonyj** [comment]
*/1 0-6 15-31 * * php -f /data/projects//xiaonuo/Admin/Shell/reportMonth.php
查了下，定时任务做的就是15-31号每天的0-6点每分钟执行

**Comment by jsonyj** [comment]
正在显示第 0 - 29 行 (共 4053 行, 查询花费 0.0046 秒)
sql优化：SELECT tb_student.id AS student_id, tmp.id FROM tb_student
LEFT JOIN (SELECT * FROM tb_report_month WHERE start = '2017-03-01 00:00:00' AND end = '2017-03-31 23:59:59' ) AS tmp  ON tb_student.id = tmp.student_id 
WHERE tb_student.deleted = 0 AND tmp.id IS NULL

**Comment by jsonyj** [comment]
SQL优化，以及将定时任务设置为每月一号早上4点执行一次
