### ISSUE TITLE
开心幼儿园刷一刷异常，部分家长收不到接送孩子信息

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#54]
有两天出现这种问题了，两天之前都没有问题的，中二班邓辰宇，妈妈微信号13882758998

**Comment by stephenwang2017** [comment]
还需要进一步的信息，第二，仍然需要接口硬件调用日志来分析

**Comment by stephenwang2017** [comment]
3月17日没有数据，其他日都有，这个和老师说的情况有出入
3月20日有push数据的-》进一步查微信接口，昨日微信接口数据正常
等待进一步反馈，对于此类问题，目前手段还不够，将来客户端将日志上传有必要

**Comment by stephenwang2017** [comment]
应该是删除主绑定家长带来的漏洞，需要在后台，以及通讯录梳理

**Comment by jsonyj** [comment]
删除主绑定家长删除仅是学生家长的关系，并未发现问题，初步诊断，不排除有设备网络较差，导致与服务器通讯失败
