### ISSUE TITLE
本周一，办公室的人都打不了卡

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#73]
1，学校那边没有反馈，即错误仅限于公司办公室
2，办公室的刷卡机是谛达诺幼儿园的，同事们生成的二维码明显是繁杂二维码，这种二维码是老版本，而谛达诺幼儿园应该使用新版幼儿园二维码。
3，查代码没查出任何东西来

**Comment by jsonyj** [comment]
查半日没查出问题，估计是有一个没有开机，怀疑主更新还是有BUG，需要密切关注
