### ISSUE TITLE
换群后无法升级

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#80]
绑定设备到群，如果该设备在别的群里面，就要把老群数据删除掉，否则就会造成获取不到最新的升级包版本

**Comment by jsonyj** [comment]
已修改，验证是否在老群有该设备，用户选择是否删除老群设备

**Comment by stephenwang2017** [comment]
换群换操作系统类型，保持不上

**Comment by jsonyj** [comment]
加入群类型定义，一个设备只能在一个操作系统群出现一次，如有冲突，提示，再次确定将删除该设备与老群的关系，并绑定到新群
