### ISSUE TITLE
红黄蓝幼儿园有的家长二维码可能有问题，识别不了

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#81]
何明轩的妈妈刷不了

**Comment by jsonyj** [comment]
可能是二维码生成时，没能生成正确的二维码。

**Comment by jsonyj** [comment]
解决方向，1.传参是否正确，2.加密过程是否正常

**Comment by stephenwang2017** [comment]
用户在没开机前打开二维码，此二维码老的，开机，此时，可能由于用户缓存导致取不到新的二维码图片。采用添加url后，添加随机数，来强制刷新。经过一3天观察，没有再发现这个问题，关闭。
