### ISSUE TITLE
性能优化:微信端，获取晨检信息，sql慢

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#85]
微信端
StudentDetectionModel.php getDetection()
Time=1.75s (1181s)  Lock=0.00s (0s)  Rows=134601.0 (90990304), root[root]@localhost
  SELECT tb_student_detection.*, tb_file.file_path as file_path
  FROM tb_student_detection
  LEFT JOIN tb_file ON  tb_student_detection.file_img_id = tb_file.id  AND tb_file.deleted = N
  WHERE tb_student_detection.deleted = N
  AND tb_student_detection.`status` = N ORDER BY created DESC

1，查微信端如何会取所有数据，怪异
2，查sql是否可以优化

**Comment by veraGe** [comment]
同"性能优化:微信端，获取晨检信息，sql慢"问题，已解决
StudentDetectionModel.php中getDetection中函数修改查询studentId查询位置

**Comment by veraGe** [comment]
同"性能优化:微信端，获取晨检信息，sql慢"问题，已解决
StudentDetectionModel.php中getDetection中函数修改查询studentId查询位置
