### ISSUE TITLE
性能优化:服务器:月报:慢

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#87]
ReportMonthModel.php getStudentList()

Time=0.59s (492s)  Lock=0.00s (0s)  Rows=1609.0 (1351573), root[root]@localhost
  SELECT tb_student.id AS student_id, tmp.id FROM tb_student 
  LEFT JOIN (SELECT * FROM tb_report_month WHERE start = 'S' AND end = 'S' ) AS tmp ON tb_student.id = tmp.student_id 
  WHERE tb_student.deleted = N AND tmp.id IS NULL

**Comment by veraGe** [comment]
已经被优化过了，0.001s。暂时没有更好的优化办法
