### ISSUE TITLE
性能优化:微信端:月报图:慢

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#89]
微信端
ChartModel.php getDetectionMonthList()
SELECT a.* FROM (SELECT *, DATE_FORMAT(created,'S') as ym FROM tb_student_detection WHERE student_id = 'S'   AND deleted = N  AND DATE_FORMAT(created,'S') >= 'S' AND DATE_FORMAT(created,'S') <= 'S'   ORDER BY id  DESC ) AS a GROUP BY a.ym

采用explain查询发现是全表扫描，所以采用函数DATE_FORMAT，必然导致全表扫描，尝试在create表上建索引，然后，日期采用unix输入，不用日期函数

**Comment by jsonyj** [comment]
正在显示第 0 - 14 行 (共 15 行, 查询花费 0.0013 秒)
查询条件：id ,420;$start=''2017-03-01 00:00:00";$end = ''2017-03-31 00:00:00"
explain全表扫描，是因为仅仅只是一张表，只能全表扫描筛选
