### ISSUE TITLE
微信端统计数据非当日数据有误

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#96]
1，默认显示当前日，一旦选择前一日，当前页面都没有数据，应该有的，点开任何子页都显示正常
2，当前页选择某个人后点亮人名的按钮，再选日期，按钮不点亮，点亮消失，应该是个错误

**Comment by veraGe** [comment]
Weichat\App\Controllers\SchoolController.php设置school_id
Weichat\Templates\School\schoolStatistic.html中传school_id回后台
