### ISSUE TITLE
性能优化：所有模块：sql采用日期函数方式都要修改

### ISSUE THREAD

**Issue by stephenwang2017** [didanoDevelopers2017/xiaonuo#98]
DATE_FORMAT( tb_student_away_record.created, '%Y-%m-%d' ) = '2017-04-11'
----->
create_time = unix_timestamp(’2014-05-29’);

**Comment by jsonyj** [comment]
针对只获取日期可以采取data()函数，针对需要计算可以使用unix_timestamp()函数,具体情况具体分析

**Comment by stephenwang2017** [comment]
确实是这样
